(()=>{'use strict';
const $=id=>document.getElementById(id),node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
let db,user,contacts=[],messages=[],selected=null,blocked=new Set(),timer,busy=false,firstLoad=true;
const isVisible=m=>!(m.sender_id===user.id?m.hidden_for_sender_at:m.hidden_for_recipient_at);
function avatar(value,cls){const n=node('span',cls);window.DT01Avatar?.render(n,value,db);return n;}
function contact(id){return contacts.find(c=>c.user_id===id);}
const status=t=>{$('dmStatus').textContent=t};
function name(id){return contacts.find(c=>c.user_id===id)?.username||'Mitglied';}
function peers(){const map=new Map();for(const m of messages){const id=m.sender_id===user.id?m.recipient_id:m.sender_id;if(!map.has(id))map.set(id,{id,last:m,unread:0});if(m.recipient_id===user.id&&!m.read_at)map.get(id).unread++}return [...map.values()].sort((a,b)=>new Date(b.last.created_at)-new Date(a.last.created_at))}
function drawContacts(){const root=$('dmContacts'),q=$('dmContactSearch').value.trim().toLocaleLowerCase('de');root.replaceChildren();const seen=new Set();const entries=[...peers(),...contacts.map(c=>({id:c.user_id,last:null,unread:0}))];for(const item of entries){if(item.id===user.id||seen.has(item.id))continue;seen.add(item.id);if(!name(item.id).toLocaleLowerCase('de').includes(q))continue;const btn=node('button','dm-contact dm-inbox-item'+(selected===item.id?' active':'')+(item.unread?' unread':''));btn.type='button';btn.dataset.user=item.id;const top=node('span','dm-inbox-top');top.append(avatar(contact(item.id)?.avatar,'dm-contact-avatar'),node('strong','',name(item.id)));if(item.unread)top.append(node('b','dm-unread-pill',String(item.unread)));btn.append(top);if(item.last){btn.append(node('span','dm-inbox-preview',(item.last.sender_id===user.id?'Du: ':'')+item.last.body));btn.append(node('small','dm-inbox-time',new Date(item.last.created_at).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'})))}else btn.append(node('span','dm-inbox-preview','Neue Unterhaltung starten'));if(blocked.has(item.id))btn.append(node('small','','⛔ Blockiert'));btn.onclick=()=>pick(item.id);root.append(btn)}if(!root.children.length)root.append(node('p','market-help','Keine Unterhaltungen gefunden.'));
const counter=$('dmInboxCount');if(counter)counter.textContent=messages.filter(m=>m.recipient_id===user.id&&!m.read_at).length+' ungelesen';}
function setRecipient(id){const h=$('dmRecipient');h.replaceChildren(avatar(contact(id)?.avatar,'dm-header-avatar'),node('span','',name(id)));}
async function pick(id){if(!id||id===user.id||!uuid.test(id))return;selected=id;setRecipient(id);$('dmBlock').hidden=false;$('dmClearThread').hidden=false;$('dmBlock').textContent=blocked.has(id)?'Entblocken':'Blockieren';$('dmBody').disabled=blocked.has(id);$('dmSend').disabled=blocked.has(id);$('dmConversation').classList.add('dm-is-open');drawContacts();await drawMessages();if(window.matchMedia('(max-width:760px)').matches)$('dmConversation').scrollIntoView({behavior:'smooth',block:'start'});}
async function drawMessages(){if(!selected)return;const root=$('dmMessages');root.replaceChildren();const thread=messages.filter(m=>(m.sender_id===selected&&m.recipient_id===user.id)||(m.sender_id===user.id&&m.recipient_id===selected)).reverse();for(const m of thread){const bubble=node('div','dm-bubble '+(m.sender_id===user.id?'out':'in'));bubble.append(node('p','',m.body),node('small','',new Date(m.created_at).toLocaleString('de-DE')));if(m.recipient_id===user.id){const report=node('button','dm-report','Melden');report.type='button';report.onclick=async()=>{if(!confirm('Nachricht melden?'))return;const {error}=await db.from('dt01_dm_reports').insert({reporter_id:user.id,message_id:m.id});status(error?'Meldung fehlgeschlagen: '+error.message:'Meldung erfasst.')};bubble.append(report)}const del=node('button','dm-delete','Löschen');del.type='button';del.title='Nachricht nur bei dir entfernen';del.onclick=()=>hideMessages([m.id],false);bubble.append(del);root.append(bubble)}if(!thread.length)root.append(node('p','market-help','Noch keine Nachrichten. Schreibe die erste Nachricht.'));root.scrollTop=root.scrollHeight;
const unread=thread.filter(m=>m.recipient_id===user.id&&!m.read_at);if(unread.length){const ids=unread.map(m=>m.id);const {error}=await db.from('dt01_dm_messages').update({read_at:new Date().toISOString()}).in('id',ids).eq('recipient_id',user.id);if(!error){const stamp=new Date().toISOString();messages.forEach(m=>{if(ids.includes(m.id))m.read_at=stamp});drawContacts();document.querySelectorAll('[data-dm-count]').forEach(e=>{const n=messages.filter(m=>m.recipient_id===user.id&&!m.read_at).length;e.textContent=n?'('+n+')':''})}else status('Unterhaltung geöffnet; Lesestatus konnte nicht gespeichert werden: '+error.message)}}
async function hideMessages(ids,all){if(!ids.length)return;const msg=all?'Gesamte Unterhaltung aus deinem Posteingang entfernen? Bei der anderen Person bleiben die Nachrichten erhalten.':'Diese Nachricht nur aus deinem Posteingang entfernen?';if(!confirm(msg))return;const btn=$('dmClearThread');if(btn)btn.disabled=true;try{const field='hidden_for_'+(user.id?'sender':'sender')+'_at';const stamp=new Date().toISOString();for(const m of messages.filter(m=>ids.includes(m.id))){const key=m.sender_id===user.id?'hidden_for_sender_at':'hidden_for_recipient_at';const {error}=await db.from('dt01_dm_messages').update({[key]:stamp}).eq('id',m.id);if(error){status('Löschen fehlgeschlagen: '+error.message+' – bitte DM_LOESCHEN_SUPABASE.sql ausführen.');return}}await loadAll();status(all?'Unterhaltung aus deinem Posteingang entfernt.':'Nachricht aus deinem Posteingang entfernt.')}finally{if(btn)btn.disabled=false}}
function drawBlocked(){const root=$('dmBlocked');root.replaceChildren();for(const id of blocked){const b=node('button','dm-contact',name(id)+' · Entblocken');b.onclick=()=>toggleBlock(id);root.append(b)}if(!blocked.size)root.append(node('small','','Keine blockierten Mitglieder'))}
async function loadBlocks(){const r=await db.from('dt01_dm_blocks').select('blocker_id,blocked_id').eq('blocker_id',user.id);blocked=new Set((r.data||[]).map(b=>b.blocked_id));drawBlocked()}
async function toggleBlock(id){if(!confirm(blocked.has(id)?'Mitglied entblocken?':'Mitglied blockieren?'))return;const query=db.from('dt01_dm_blocks');const {error}=blocked.has(id)?await query.delete().eq('blocker_id',user.id).eq('blocked_id',id):await query.insert({blocker_id:user.id,blocked_id:id});if(error)return status(error.message);await loadBlocks();if(selected===id)await pick(id)}
async function loadAll(){if(busy)return;busy=true;try{const r=await db.from('dt01_dm_messages').select('id,sender_id,recipient_id,listing_id,body,created_at,read_at,hidden_for_sender_at,hidden_for_recipient_at').or('sender_id.eq.'+user.id+',recipient_id.eq.'+user.id).order('created_at',{ascending:false}).limit(1000);if(r.error){status('Nachrichten nicht verfügbar: '+r.error.message);return}messages=(r.data||[]).filter(isVisible);if(firstLoad){firstLoad=false;const params=new URLSearchParams(location.search),to=params.get('to');if(to&&uuid.test(to)&&to!==user.id)selected=to;else{const unread=peers().filter(p=>p.unread>0);selected=(unread[0]||peers()[0])?.id||null}}drawContacts();if(selected){setRecipient(selected);$('dmBlock').hidden=false;$('dmClearThread').hidden=false;$('dmBlock').textContent=blocked.has(selected)?'Entblocken':'Blockieren';$('dmBody').disabled=blocked.has(selected);$('dmSend').disabled=blocked.has(selected);await drawMessages()}status(messages.length?'Posteingang aktualisiert':'Noch keine Nachrichten vorhanden. Wähle links ein Mitglied aus.')}finally{busy=false}}
async function refreshContacts(){const p=await db.from('dt01_member_profiles').select('user_id,username,avatar');if(!p.error){contacts=p.data||[];window.DT01Avatar?.invalidate();drawContacts();if(selected)setRecipient(selected)}}
async function init(){for(let i=0;i<45&&!window.DT01Cloud?.client();i++)await new Promise(r=>setTimeout(r,100));db=window.DT01Cloud?.client();if(!db)return status('Cloud nicht verfügbar.');const {data:{session}}=await db.auth.getSession();user=session?.user;if(!user){status('Bitte zuerst anmelden, um deine privaten Nachrichten zu öffnen.');return}$('dmPrivate').hidden=false;const p=await db.from('dt01_member_profiles').select('user_id,username,avatar');if(p.error)return status('Mitglieder nicht verfügbar: '+p.error.message);contacts=p.data||[];await loadBlocks();await loadAll();window.addEventListener('focus',refreshContacts);window.addEventListener('dt01:profile-updated',refreshContacts);$('dmContactSearch').oninput=drawContacts;$('dmBlock').onclick=()=>selected&&toggleBlock(selected);$('dmClearThread').onclick=()=>selected&&hideMessages(messages.filter(m=>(m.sender_id===selected&&m.recipient_id===user.id)||(m.sender_id===user.id&&m.recipient_id===selected)).map(m=>m.id),true);$('dmForm').onsubmit=async e=>{e.preventDefault();if(!selected||blocked.has(selected))return;const body=$('dmBody').value.trim();if(!body)return;const btn=$('dmSend');btn.disabled=true;const params=new URLSearchParams(location.search),listing=params.get('listing');const payload={sender_id:user.id,recipient_id:selected,body};if(listing&&uuid.test(listing))payload.listing_id=listing;const {error}=await db.from('dt01_dm_messages').insert(payload);btn.disabled=false;if(error)return status('Senden fehlgeschlagen: '+error.message);$('dmBody').value='';await loadAll()};timer=setInterval(()=>{if(!document.hidden)loadAll()},10000);window.addEventListener('pagehide',()=>clearInterval(timer))}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
