(()=>{'use strict';
const $=id=>document.getElementById(id), PREFIX='wfb-droid-tycoon-v3-', D=window.TRACKER_DATA||{};
const kinds={droids:{label:'Droiden',items:D.droids||[],url:'droids.html'},fusionen:{label:'Fusionen',items:D.fusionDroids||[],url:'fusionen.html'},icons:{label:'Ikonen',items:D.icons||[],url:'ikonen.html'}};
let key=PREFIX+'missions-guest',missions=[],cloud=null,cloudUser=null,remoteReady=false,syncTimer=null,deletedIds=new Set();
const read=(k)=>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return {}}};
const getMissions=()=>{try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x:[]}catch{return []}};
const save=()=>{localStorage.setItem(key,JSON.stringify(missions));scheduleSync()};
function scheduleSync(){if(!cloudUser||!remoteReady)return;clearTimeout(syncTimer);syncTimer=setTimeout(syncMissions,450)}
async function syncMissions(){if(!cloudUser||!cloud||!navigator.onLine)return;const uid=cloudUser.id;try{const {data,error}=await cloud.from('player_missions').select('mission_id,payload,updated_at').eq('user_id',uid);if(error)throw error;const remote=new Map((data||[]).map(r=>[r.mission_id,r]));const local=new Map(missions.map(m=>[m.id,m]));const changes=[];for(const [id,r] of remote){const mine=local.get(id);const remoteTime=new Date(r.updated_at).getTime();if(!mine||remoteTime>(mine.updated||mine.created||0)){if(r.payload?.deleted){local.delete(id);deletedIds.add(id)}else local.set(id,{...r.payload,updated:remoteTime})}}for(const [id,m] of local){const r=remote.get(id);if(!r||((m.updated||m.created||0)>new Date(r.updated_at).getTime()+1000))changes.push({user_id:uid,mission_id:id,payload:m,updated_at:new Date(m.updated||m.created||Date.now()).toISOString()})}for(const id of deletedIds){const r=remote.get(id);if(!r||!r.payload?.deleted)changes.push({user_id:uid,mission_id:id,payload:{deleted:true},updated_at:new Date().toISOString()})}if(changes.length){const {error:err}=await cloud.from('player_missions').upsert(changes,{onConflict:'user_id,mission_id'});if(err)throw err}missions=[...local.values()];localStorage.setItem(key,JSON.stringify(missions));draw();const info=$('mc-storage');if(info)info.textContent='☁ Missionen werden mit deinem Konto synchronisiert. Offline-Änderungen bleiben lokal gespeichert.';}catch(e){console.warn('Mission sync:',e);const info=$('mc-storage');if(info)info.textContent='⚠ Missions-Cloud nicht erreichbar. Änderungen bleiben lokal. Bitte SQL-Setup prüfen.'}}
function count(kind){if(kind==='all')return Object.keys(kinds).reduce((sum,k)=>sum+count(k),0);const {items}=kinds[kind];const state=read(PREFIX+kind);return items.reduce((sum,it,i)=>{const root=it.name+'#'+i;const found=kind==='icons'?!!state[root]:(D.variants||[]).some(v=>!!state[root+'|'+v]);return sum+(found?1:0)},0)}
function periodEnd(period){const now=new Date();if(period==='today'){const d=new Date(now);d.setHours(23,59,59,999);return d.getTime()}if(period==='week'){const d=new Date(now);d.setDate(d.getDate()+((7-d.getDay())%7));d.setHours(23,59,59,999);return d.getTime()}return null}
function el(tag,cls,txt){const e=document.createElement(tag);if(cls)e.className=cls;if(txt!==undefined)e.textContent=txt;return e}
function draw(){const active=$('mc-active'),archive=$('mc-archive');active.replaceChildren();archive.replaceChildren();let changed=false;
for(const m of missions){if(!m.status){const gain=Math.max(0,count(m.kind)-m.baseline);if(gain>=m.target){m.status='done';m.finished=Date.now();m.updated=Date.now();changed=true}else if(m.deadline&&Date.now()>m.deadline){m.status='expired';m.finished=Date.now();m.updated=Date.now();changed=true}}}
if(changed)save();let a=0,b=0;for(const m of missions.slice().reverse()){
const done=m.status==='done',expired=m.status==='expired',archived=done||expired;
if(archived)b++;else a++;
const progress=done?m.target:Math.min(m.target,Math.max(0,count(m.kind)-m.baseline));const card=el('article','mc-card'+(archived?' mc-archived':''));
const top=el('div','mc-card-head'),name=el('strong','',m.title),badge=el('span','mc-pill',done?'✓ ABGESCHLOSSEN':expired?'ZEIT ABGELAUFEN':m.period==='today'?'HEUTE':m.period==='week'?'DIESE WOCHE':'OHNE LIMIT');top.append(name,badge);card.append(top);
card.append(el('p','mc-sub', (m.kind==='all'?'Alle Sammlungen':kinds[m.kind]?.label||'Sammlung')+' · '+progress+' von '+m.target+' neuen Einträgen'));
const track=el('div','mc-track'),fill=el('div','mc-fill');fill.style.width=(100*progress/m.target)+'%';track.append(fill);card.append(track);
const actions=el('div','mc-actions');if(!archived){const link=el('a','mc-button mc-small','SAMMLUNG ÖFFNEN ↗');link.href=m.kind==='all'?'./index.html':'./'+kinds[m.kind].url;actions.append(link)}
const remove=el('button','mc-danger', 'LÖSCHEN');remove.type='button';remove.addEventListener('click',()=>{if(confirm('Mission wirklich löschen?')){missions=missions.filter(x=>x.id!==m.id);deletedIds.add(m.id);save();draw()}});actions.append(remove);card.append(actions);(archived?archive:active).append(card)}
$('mc-active-count').textContent=a+' aktiv';$('mc-archive-count').textContent=b+' archiviert';$('mc-summary').textContent=a+' aktive Missionen  ·  '+missions.filter(m=>m.status==='done').length+' abgeschlossen';if(!a)active.append(el('p','mc-empty','Noch keine aktive Mission. Starte oben mit einem Sammelziel!'));if(!b)archive.append(el('p','mc-empty','Abgeschlossene und abgelaufene Missionen erscheinen hier.'))}
function create(title,kind,target,period){const baseline=count(kind),max=kind==='all'?Object.values(kinds).reduce((a,k)=>a+k.items.length,0):kinds[kind].items.length;if(target<1||!Number.isInteger(target)||target>999){alert('Bitte eine gültige Zielzahl zwischen 1 und 999 eingeben.');return}if(target>max-baseline){alert('Es gibt nur '+(max-baseline)+' noch fehlende Einträge in dieser Sammlung.');return}missions.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random(),title:title.trim(),kind,target,period,baseline,deadline:periodEnd(period),created:Date.now(),updated:Date.now(),status:''});save();draw()}
$('mc-form').addEventListener('submit',e=>{e.preventDefault();create($('mc-title').value,$('mc-kind').value,Number($('mc-target').value),$('mc-period').value);$('mc-title').value=''});
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const [kind,n,period]=b.dataset.preset.split(':');create(n+' neue '+kinds[kind].label+' sammeln',kind,Number(n),period)}));
async function init(){try{let tries=0;while(!window.DT01Cloud?.client()&&tries++<35)await new Promise(r=>setTimeout(r,120));cloud=window.DT01Cloud?.client()||null;cloudUser=window.DT01Cloud?.user()||null;if(cloudUser){key=PREFIX+'missions-user-'+cloudUser.id;remoteReady=true}}catch(e){console.warn(e)}missions=getMissions();draw();if(cloudUser)syncMissions();if(cloud){cloud.auth.onAuthStateChange((_event,session)=>{const id=session?.user?.id||null;if(id===cloudUser?.id)return;cloudUser=session?.user||null;key=PREFIX+(cloudUser?'missions-user-'+cloudUser.id:'missions-guest');missions=getMissions();deletedIds.clear();remoteReady=!!cloudUser;draw();if(cloudUser)setTimeout(syncMissions,300)})}window.addEventListener('storage',e=>{if(e.key===key){missions=getMissions();draw()}});window.addEventListener('focus',()=>{draw();if(cloudUser)syncMissions()});window.addEventListener('online',()=>{if(cloudUser)syncMissions()});document.addEventListener('visibilitychange',()=>{if(!document.hidden){draw();if(cloudUser)syncMissions()}});setInterval(()=>{draw();if(cloudUser)syncMissions()},30000)}
init();})();